// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectFill.Domain.StaticData;

namespace ProjectFill.Domain.Interfaces;

public partial interface IStaticDataService
{
    AdPlacementData? GetAdPlacement(int id);
    IReadOnlyList<AdPlacementData> GetAllAdPlacements();
    AvatarData? GetAvatar(int id);
    IReadOnlyList<AvatarData> GetAllAvatars();
    ColorPaletteData? GetColorPalette(byte id);
    IReadOnlyList<ColorPaletteData> GetAllColorPalettes();
    CurrencyData? GetCurrency(int id);
    IReadOnlyList<CurrencyData> GetAllCurrencys();
    ItemData? GetItem(int id);
    IReadOnlyList<ItemData> GetAllItems();
    RewardGroupData? GetRewardGroup(int reward_group_id);
    IReadOnlyList<RewardGroupData> GetAllRewardGroups();
    RewardItemData? GetRewardItem(int id);
    IReadOnlyList<RewardItemData> GetAllRewardItems();
    RewardSourceData? GetRewardSource(int id);
    IReadOnlyList<RewardSourceData> GetAllRewardSources();
    IapProductData? GetIapProduct(int info_id);
    IReadOnlyList<IapProductData> GetAllIapProducts();
    ChapterData? GetChapter(int chapter_id);
    IReadOnlyList<ChapterData> GetAllChapters();
    StageData? GetStage(int stage_id);
    IReadOnlyList<StageData> GetAllStages();
}