// AUTO-GENERATED by gen:data — do not edit
#nullable enable
using ProjectFill.Domain.StaticData;

namespace ProjectFill.Domain.Interfaces;

public partial interface IStaticDataService
{
    AchievementData? GetAchievement(string achievement_id);
    IReadOnlyList<AchievementData> GetAllAchievements();
    AdPlacementData? GetAdPlacement(int id);
    IReadOnlyList<AdPlacementData> GetAllAdPlacements();
    AvatarData? GetAvatar(int id);
    IReadOnlyList<AvatarData> GetAllAvatars();
    ColorPaletteData? GetColorPalette(byte id);
    IReadOnlyList<ColorPaletteData> GetAllColorPalettes();
    CosmeticItemData? GetCosmeticItem(string cosmetic_id);
    IReadOnlyList<CosmeticItemData> GetAllCosmeticItems();
    CurrencyData? GetCurrency(int id);
    IReadOnlyList<CurrencyData> GetAllCurrencys();
    DailyLoginMilestoneData? GetDailyLoginMilestone(int id);
    IReadOnlyList<DailyLoginMilestoneData> GetAllDailyLoginMilestones();
    DailyLoginRewardData? GetDailyLoginReward(int id);
    IReadOnlyList<DailyLoginRewardData> GetAllDailyLoginRewards();
    WeeklyMissionPoolData? GetWeeklyMissionPool(string mission_id);
    IReadOnlyList<WeeklyMissionPoolData> GetAllWeeklyMissionPools();
    WeeklyMissionTrackData? GetWeeklyMissionTrack(int ep_threshold);
    IReadOnlyList<WeeklyMissionTrackData> GetAllWeeklyMissionTracks();
    ItemData? GetItem(int id);
    IReadOnlyList<ItemData> GetAllItems();
    RewardGroupData? GetRewardGroup(int reward_group_id);
    IReadOnlyList<RewardGroupData> GetAllRewardGroups();
    RewardItemData? GetRewardItem(int id);
    IReadOnlyList<RewardItemData> GetAllRewardItems();
    RewardSourceData? GetRewardSource(int id);
    IReadOnlyList<RewardSourceData> GetAllRewardSources();
    IapProductData? GetIapProduct(int info_id);
    IReadOnlyList<IapProductData> GetAllIapProducts();
    ChapterData? GetChapter(int chapter_id);
    IReadOnlyList<ChapterData> GetAllChapters();
    StageData? GetStage(int stage_id);
    IReadOnlyList<StageData> GetAllStages();
}