-- Generated by db-generator | DB: mysql | 2026-06-18T07:09:47.326Z

CREATE TABLE IF NOT EXISTS `weekly_mission_sets` (
  `week_start_date` VARCHAR(10) NOT NULL,
  `mission_ids` VARCHAR(256) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`week_start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='One global Weekly Mission Event mission set per week (Monday 00:00 UTC). Deterministically seeded from week_start_date. mission_ids holds the assigned 5 mission_id values.';

CREATE TABLE IF NOT EXISTS `user_weekly_missions` (
  `user_id` BIGINT NOT NULL,
  `week_start_date` VARCHAR(10) NOT NULL,
  `mission_id` VARCHAR(32) NOT NULL,
  `progress` INT NOT NULL DEFAULT 0,
  `is_completed` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `week_start_date`, `mission_id`),
  KEY `idx_user_weekly_missions_week` (`user_id`, `week_start_date`),
  CONSTRAINT `fk_user_weekly_missions_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player per-week mission progress. Aggregated in the stage-clear flow with no submit endpoint.';

CREATE TABLE IF NOT EXISTS `user_weekly_mission_state` (
  `user_id` BIGINT NOT NULL,
  `week_start_date` VARCHAR(10) NOT NULL,
  `total_ep` INT NOT NULL DEFAULT 0,
  `claimed_thresholds` VARCHAR(128) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `week_start_date`),
  CONSTRAINT `fk_user_weekly_mission_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player per-week Weekly Mission Event state: cumulative EP + claimed milestone thresholds (CSV).';

-- user_ranking_totals: removed from schema (review before applying):
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_earned_stars`;
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_stars_achieved_at`;
-- ALTER TABLE `user_ranking_totals` DROP INDEX `idx_user_ranking_totals_stars`;

-- Table removed from schema (review before applying):
-- DROP TABLE IF EXISTS `daily_challenges`;

-- Table removed from schema (review before applying):
-- DROP TABLE IF EXISTS `user_challenge_streaks`;

-- Table removed from schema (review before applying):
-- DROP TABLE IF EXISTS `user_daily_challenge_records`;
