-- Generated by db-generator | DB: mysql | 2026-06-16T10:57:14.343Z

CREATE TABLE IF NOT EXISTS `user_achievements` (
  `user_id` BIGINT NOT NULL,
  `achievement_id` VARCHAR(32) NOT NULL,
  `progress` INT NOT NULL DEFAULT 0,
  `is_completed` TINYINT(1) NOT NULL DEFAULT 0,
  `completed_at` DATETIME(6) NULL,
  `reward_claimed` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `achievement_id`),
  KEY `idx_user_achievements_user_id` (`user_id`),
  CONSTRAINT `fk_user_achievements_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player achievement progress and claim state.';
