-- Generated by db-generator | DB: mysql | 2026-06-16T17:42:29.304Z

CREATE TABLE IF NOT EXISTS `user_stage_progress` (
  `user_id` BIGINT NOT NULL,
  `stage_id` INT NOT NULL,
  `stage_clear` TINYINT(1) NOT NULL DEFAULT 0,
  `best_moves_used` INT NOT NULL DEFAULT 0,
  `latest_moves_used` INT NOT NULL DEFAULT 0,
  `first_cleared_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `stage_id`),
  KEY `idx_user_stage_progress_stage_moves` (`stage_id`, `best_moves_used`),
  CONSTRAINT `fk_user_stage_progress_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player per-stage Signal Sort campaign progress. Source of truth for clear state, best/latest moves, and stage-moves ranking.';

CREATE TABLE IF NOT EXISTS `user_weekly_ranking` (
  `user_id` BIGINT NOT NULL,
  `week_start_date` VARCHAR(10) NOT NULL,
  `weekly_cleared_count` INT NOT NULL DEFAULT 0,
  `weekly_cleared_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `idx_user_weekly_ranking_rank` (`week_start_date`, `weekly_cleared_count`, `weekly_cleared_at`),
  CONSTRAINT `fk_user_weekly_ranking_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player weekly cleared-stage aggregate. Resets each Monday 00:00 UTC via week_start_date rollover.';

ALTER TABLE `user_ranking_totals`
  ADD COLUMN `total_cleared_stages` INT NOT NULL DEFAULT 0,
  ADD COLUMN `total_cleared_at` DATETIME(6) NULL,
  ADD INDEX `idx_user_ranking_totals_cleared_stages` (`total_cleared_stages`, `total_cleared_at`);

-- user_ranking_totals: removed from schema (review before applying):
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_earned_stars`;
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_stars_achieved_at`;
-- ALTER TABLE `user_ranking_totals` DROP INDEX `idx_user_ranking_totals_stars`;
