-- Generated by db-generator | DB: mysql | 2026-06-17T05:37:29.801Z

ALTER TABLE `user_ranking_totals`
  ADD COLUMN `perfect_clears` INT NOT NULL DEFAULT 0,
  ADD COLUMN `perfect_cleared_at` DATETIME(6) NULL,
  ADD INDEX `idx_user_ranking_totals_perfect` (`perfect_clears`, `perfect_cleared_at`);

-- user_ranking_totals: removed from schema (review before applying):
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_earned_stars`;
-- ALTER TABLE `user_ranking_totals` DROP COLUMN `total_stars_achieved_at`;
-- ALTER TABLE `user_ranking_totals` DROP INDEX `idx_user_ranking_totals_stars`;

ALTER TABLE `user_stage_progress`
  ADD COLUMN `is_perfect` TINYINT(1) NOT NULL DEFAULT 0;
