-- Generated by db-generator | DB: mysql | 2026-06-15T17:31:56.673Z

CREATE TABLE IF NOT EXISTS `players` (
  `user_id` BIGINT NOT NULL,
  `platform_pid` VARCHAR(24) NULL,
  `display_name` VARCHAR(64) NOT NULL,
  `avatar_id` INT NOT NULL DEFAULT 1,
  `equipped_board_theme_id` INT NOT NULL DEFAULT 1,
  `account_created_at` DATETIME(6) NOT NULL,
  `last_login_at` DATETIME(6) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `conflict_cloud_pid` VARCHAR(24) NULL,
  `is_no_ads` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `ux_players_platform_pid` (`platform_pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Game-local player record. platform_pid is the 24-char public cross-reference from platform-auth JWT sub.';

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `session_id` VARCHAR(24) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_sessions_session_id` (`session_id`),
  CONSTRAINT `fk_sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `tr_id` INT NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `params` JSON NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_event_logs_user_id` (`user_id`),
  KEY `idx_event_logs_tr_id` (`tr_id`),
  KEY `idx_event_logs_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_event_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Audit log for all user-modifying API calls.';

CREATE TABLE IF NOT EXISTS `user_reward_claim_state` (
  `user_id` BIGINT NOT NULL,
  `source_id` VARCHAR(64) NOT NULL,
  `period_key` VARCHAR(32) NOT NULL,
  `claim_count` INT NOT NULL DEFAULT 0,
  `last_claimed_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `source_id`, `period_key`),
  KEY `idx_reward_claim_state_user_id` (`user_id`),
  CONSTRAINT `fk_user_reward_claim_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player reward source claim state. Event history is stored in event_logs.';

CREATE TABLE IF NOT EXISTS `ad_reward_transactions` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `placement_id` VARCHAR(64) NOT NULL,
  `reward_type` VARCHAR(32) NOT NULL,
  `reward_value` INT NOT NULL,
  `context_type` VARCHAR(32) NULL,
  `context_id` VARCHAR(128) NULL,
  `provider` VARCHAR(32) NOT NULL,
  `provider_tx_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `verified_at` DATETIME(6) NULL,
  `granted_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ad_reward_provider_tx` (`provider`, `provider_tx_id`),
  KEY `idx_ad_reward_user_id` (`user_id`),
  KEY `idx_ad_reward_context` (`context_type`, `context_id`),
  KEY `idx_ad_reward_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_ad_reward_transactions_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Common rewarded-ad transaction table for idempotent verification and grant history.';

CREATE TABLE IF NOT EXISTS `user_interstitial_state` (
  `user_id` BIGINT NOT NULL,
  `last_shown_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_interstitial_state_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracks last interstitial shown time per player for cooldown enforcement.';

CREATE TABLE IF NOT EXISTS `user_currency` (
  `user_id` BIGINT NOT NULL,
  `soft_amount` BIGINT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_currency_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Soft currency balance per player.';

CREATE TABLE IF NOT EXISTS `user_ranking_totals` (
  `user_id` BIGINT NOT NULL,
  `total_earned_stars` INT NOT NULL DEFAULT 0,
  `total_stars_achieved_at` DATETIME(6) NULL,
  `max_cleared_stage_id` INT NOT NULL DEFAULT 0,
  `max_stage_achieved_at` DATETIME(6) NULL,
  `win_streak` INT NOT NULL DEFAULT 0,
  `max_win_streak` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `idx_user_ranking_totals_stars` (`total_earned_stars`, `total_stars_achieved_at`),
  KEY `idx_user_ranking_totals_max_stage` (`max_cleared_stage_id`, `max_stage_achieved_at`),
  CONSTRAINT `fk_user_ranking_totals_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player global ranking aggregates rebuilt from user_stage_progress if Redis is lost.';

CREATE TABLE IF NOT EXISTS `user_inventory` (
  `user_id` BIGINT NOT NULL,
  `item_id` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`),
  KEY `idx_user_inventory_user_id` (`user_id`),
  CONSTRAINT `fk_user_inventory_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inventory counts for each booster item type per player.';

CREATE TABLE IF NOT EXISTS `user_tutorial_progress` (
  `user_id` BIGINT NOT NULL,
  `tutorial_id` INT NOT NULL,
  `viewed_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `tutorial_id`),
  KEY `idx_user_tutorial_progress_user_id` (`user_id`),
  CONSTRAINT `fk_user_tutorial_progress_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracks completed tutorial steps per user.';

CREATE TABLE IF NOT EXISTS `currency_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `currency_type` VARCHAR(32) NOT NULL,
  `delta` BIGINT NOT NULL,
  `balance_before` BIGINT NOT NULL,
  `balance_after` BIGINT NOT NULL,
  `reason` VARCHAR(256) NOT NULL,
  `correlation_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_currency_logs_user_id` (`user_id`),
  KEY `idx_currency_logs_correlation_id` (`correlation_id`),
  CONSTRAINT `fk_currency_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Append-only audit log for all soft currency mutations. Never UPDATE or DELETE.';

CREATE TABLE IF NOT EXISTS `iap_purchases` (
  `purchase_id` VARCHAR(36) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `info_id` INT NOT NULL DEFAULT 0,
  `product_id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(128) NOT NULL,
  `purchase_token` VARCHAR(512) NOT NULL,
  `price` DOUBLE NOT NULL,
  `currency` VARCHAR(8) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `platform` VARCHAR(32) NOT NULL,
  `raw_receipt` VARCHAR(2048) NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`purchase_id`),
  UNIQUE KEY `uq_iap_purchases_order` (`platform`, `order_id`),
  KEY `idx_iap_purchases_user` (`user_id`),
  CONSTRAINT `fk_iap_purchases_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='In-app purchase verification and CS logs.';

CREATE TABLE IF NOT EXISTS `user_iap_purchase_counts` (
  `user_id` BIGINT NOT NULL,
  `info_id` INT NOT NULL,
  `purchase_count` INT NOT NULL DEFAULT 0,
  `period_start` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `info_id`),
  KEY `idx_user_iap_purchase_counts_user_id` (`user_id`),
  CONSTRAINT `fk_user_iap_purchase_counts_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-user per-product purchase count for limit enforcement and lazy period reset.';
