-- Generated by db-generator | DB: mysql | 2026-06-16T11:03:41.563Z

CREATE TABLE IF NOT EXISTS `user_daily_challenge_records` (
  `user_id` BIGINT NOT NULL,
  `challenge_date` VARCHAR(10) NOT NULL,
  `moves_used` INT NOT NULL DEFAULT 0,
  `clear_time_seconds` INT NOT NULL DEFAULT 0,
  `is_cleared` TINYINT(1) NOT NULL DEFAULT 0,
  `streak_at_clear` INT NOT NULL DEFAULT 0,
  `reward_claimed` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `challenge_date`),
  KEY `idx_challenge_records_ranking` (`challenge_date`, `moves_used`, `clear_time_seconds`),
  CONSTRAINT `fk_user_daily_challenge_records_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player daily challenge attempt result, ranking source for the date.';

CREATE TABLE IF NOT EXISTS `user_challenge_streaks` (
  `user_id` BIGINT NOT NULL,
  `current_streak` INT NOT NULL DEFAULT 0,
  `best_streak` INT NOT NULL DEFAULT 0,
  `last_clear_date` VARCHAR(10) NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_challenge_streaks_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-player daily challenge consecutive-clear streak.';
