-- Generated by db-generator | DB: mysql | 2026-06-16T10:41:14.317Z

CREATE TABLE IF NOT EXISTS `user_cosmetics` (
  `user_id` BIGINT NOT NULL,
  `cosmetic_id` VARCHAR(32) NOT NULL,
  `unlocked_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`, `cosmetic_id`),
  KEY `idx_user_cosmetics_user_id` (`user_id`),
  CONSTRAINT `fk_user_cosmetics_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cosmetics unlocked (owned) by each player.';

CREATE TABLE IF NOT EXISTS `user_active_cosmetics` (
  `user_id` BIGINT NOT NULL,
  `active_chip_skin` VARCHAR(32) NOT NULL DEFAULT 'chip_default',
  `active_lane_skin` VARCHAR(32) NOT NULL DEFAULT 'lane_default',
  `active_board_skin` VARCHAR(32) NOT NULL DEFAULT 'board_default',
  `use_custom_board_skin` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_active_cosmetics_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Currently equipped cosmetic skins per player.';
