-- Generated by db-generator | DB: mysql | 2026-06-16T10:49:20.578Z

CREATE TABLE IF NOT EXISTS `user_login_attendance` (
  `user_id` BIGINT NOT NULL,
  `current_day` INT NOT NULL DEFAULT 0,
  `current_cycle` INT NOT NULL DEFAULT 1,
  `current_streak` INT NOT NULL DEFAULT 0,
  `best_streak` INT NOT NULL DEFAULT 0,
  `total_attended_days` INT NOT NULL DEFAULT 0,
  `last_attended_date` DATETIME(6) NULL,
  `reward_claimed_today` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_login_attendance_user_id` FOREIGN KEY (`user_id`) REFERENCES `players` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Daily attendance state per player. Non-punitive 7-day cycle, only streak resets on a missed day.';
