// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/string/client_string.csv
#if UNITY_EDITOR
namespace Game.Editor
{
    // Keys from client_string.csv — import with: using static Game.Editor.StringIds
    internal static class StringIds
    {
        // app
        public const string AppTitle = "app.title";

        // boot
        public const string BootLoading = "boot.loading";
        public const string BootNewGuestSession = "boot.new_guest_session";
        public const string BootForceUpdateTitle = "boot.force_update.title";
        public const string BootForceUpdateBody = "boot.force_update.body";
        public const string BootForceUpdateBtn = "boot.force_update.btn";

        // common
        public const string CommonBtnCancel = "common.btn_cancel";
        public const string CommonBtnConfirm = "common.btn_confirm";
        public const string CommonBtnOk = "common.btn_ok";
        public const string CommonBtnRetry = "common.btn_retry";
        public const string CommonBtnNext = "common.btn_next";
        public const string CommonBtnPlay = "common.btn_play";
        public const string CommonBtnClose = "common.btn_close";
        public const string CommonBtnMap = "common.btn_map";
        public const string CommonSettings = "common.settings";
        public const string CommonGuest = "common.guest";
        public const string CommonBtnClaim = "common.btn_claim";
        public const string CommonLoading = "common.loading";
        public const string CommonGold = "common.gold";
        public const string CommonBtnUnlock = "common.btn_unlock";
        public const string CommonBtnSwitch = "common.btn_switch";
        public const string CommonBtnExit = "common.btn_exit";

        // error
        public const string ErrorNetworkCheck = "error.network_check";
        public const string ErrorAdFailed = "error.ad_failed";
        public const string ErrorServerUnstable = "error.server_unstable";

        // popup
        public const string PopupNetworkErrorTitle = "popup.network_error.title";
        public const string PopupRewardTitle = "popup.reward.title";
        public const string PopupReloginTitle = "popup.relogin.title";
        public const string PopupReloginBtnRelogin = "popup.relogin.btn_relogin";
        public const string PopupReloginBtnGuest = "popup.relogin.btn_guest";
        public const string PopupResultTitle = "popup.result.title";
        public const string PopupStuckTitle = "popup.stuck.title";
        public const string PopupStuckBody = "popup.stuck.body";
        public const string PopupFailBtnForfeit = "popup.fail.btn_forfeit";
        public const string PopupPauseTitle = "popup.pause.title";
        public const string PopupPauseBtnResume = "popup.pause.btn_resume";
        public const string PopupPauseBtnRestart = "popup.pause.btn_restart";
        public const string PopupPauseBtnStageSelect = "popup.pause.btn_stage_select";
        public const string PopupSettingsBgm = "popup.settings.bgm";
        public const string PopupSettingsSfx = "popup.settings.sfx";
        public const string PopupSettingsScreenShake = "popup.settings.screen_shake";
        public const string PopupSettingsAccount = "popup.settings.account";
        public const string PopupAccountBtnLink = "popup.account.btn_link";
        public const string PopupAccountBtnSwitch = "popup.account.btn_switch";
        public const string PopupAccountRestartTitle = "popup.account_restart.title";
        public const string PopupAccountRestartBody = "popup.account_restart.body";
        public const string PopupAccountRestartConfirm = "popup.account_restart.confirm";
        public const string PopupAccountConflictTitle = "popup.account_conflict.title";
        public const string PopupAccountConflictBody = "popup.account_conflict.body";
        public const string PopupAccountConflictLocalLabel = "popup.account_conflict.local_label";
        public const string PopupAccountConflictCloudLabel = "popup.account_conflict.cloud_label";
        public const string PopupAccountConflictStageFmt = "popup.account_conflict.stage_fmt";
        public const string PopupAccountConflictGoldFmt = "popup.account_conflict.gold_fmt";
        public const string PopupAccountConflictClearedFmt = "popup.account_conflict.cleared_fmt";
        public const string PopupAccountConflictItemsFmt = "popup.account_conflict.items_fmt";
        public const string PopupAccountConflictBtnKeepLocal = "popup.account_conflict.btn_keep_local";
        public const string PopupAccountConflictBtnKeepCloud = "popup.account_conflict.btn_keep_cloud";
        public const string PopupStageInfoTitle = "popup.stage_info.title";
        public const string PopupStageInfoBestMoves = "popup.stage_info.best_moves";
        public const string PopupStageInfoNoRecord = "popup.stage_info.no_record";
        public const string PopupStageInfoBestNone = "popup.stage_info.best_none";
        public const string PopupStageInfoOwnedItems = "popup.stage_info.owned_items";
        public const string PopupStageInfoItemCountFmt = "popup.stage_info.item_count_fmt";
        public const string PopupResultFailed = "popup.result.failed";
        public const string PopupResultClearTitle = "popup.result.clear_title";
        public const string PopupResultMoves = "popup.result.moves";
        public const string PopupResultBestMoves = "popup.result.best_moves";
        public const string PopupResultRank = "popup.result.rank";
        public const string PopupResultNewBest = "popup.result.new_best";
        public const string PopupStuckBtnAddLaneAd = "popup.stuck.btn_add_lane_ad";
        public const string PopupPauseBtnHowToPlay = "popup.pause.btn_how_to_play";
        public const string PopupAccountBtnSave = "popup.account.btn_save";
        public const string PopupAccountLabelNickname = "popup.account.label_nickname";
        public const string PopupAccountLabelSelectAvatar = "popup.account.label_select_avatar";
        public const string PopupAccountTabAvatars = "popup.account.tab_avatars";
        public const string PopupAccountTabBoardSkins = "popup.account.tab_board_skins";
        public const string PopupAccountPlaceholderNickname = "popup.account.placeholder_nickname";
        public const string PopupBuyTitle = "popup.buy.title";
        public const string PopupBuyCostFmt = "popup.buy.cost_fmt";
        public const string PopupBuyGoldFmt = "popup.buy.gold_fmt";
        public const string PopupFailWatchAd = "popup.fail.watch_ad";
        public const string PopupSettingsHaptic = "popup.settings.haptic";
        public const string PopupSettingsLanguage = "popup.settings.language";
        public const string PopupSettingsLangKO = "popup.settings.lang.KO";
        public const string PopupSettingsLangEN = "popup.settings.lang.EN";
        public const string PopupStuckShuffleCostFmt = "popup.stuck.shuffle_cost_fmt";
        public const string PopupAccountConfirmUnlockThemeTitle = "popup.account.confirm_unlock_theme_title";
        public const string PopupAccountConfirmUnlockThemeBodyFmt = "popup.account.confirm_unlock_theme_body_fmt";
        public const string PopupAccountConfirmFailedUnlockTheme = "popup.account.confirm_failed_unlock_theme";
        public const string PopupAccountConfirmUnlockAvatarTitle = "popup.account.confirm_unlock_avatar_title";
        public const string PopupAccountConfirmUnlockAvatarBodyFmt = "popup.account.confirm_unlock_avatar_body_fmt";
        public const string PopupAccountConfirmFailedUnlockAvatar = "popup.account.confirm_failed_unlock_avatar";
        public const string PopupAccountConfirmSwitchTitle = "popup.account.confirm_switch_title";
        public const string PopupAccountConfirmSwitchBody = "popup.account.confirm_switch_body";
        public const string PopupStuckRestartBody = "popup.stuck.restart_body";
        public const string PopupStuckAddLaneAdBody = "popup.stuck.add_lane_ad_body";
        public const string PopupAccountChooseAvatar = "popup.account.choose_avatar";
        public const string PopupAccountChooseBoardTheme = "popup.account.choose_board_theme";
        public const string PopupBootContinueAsGuestTitle = "popup.boot.continue_as_guest_title";
        public const string PopupBootContinueAsGuestBody = "popup.boot.continue_as_guest_body";
        public const string PopupResultDoubleReward = "popup.result.double_reward";
        public const string PopupAttendanceTitle = "popup.attendance.title";
        public const string PopupAttendanceTodayReward = "popup.attendance.today_reward";
        public const string PopupAttendanceBtnClaim = "popup.attendance.btn_claim";
        public const string PopupAttendanceDayFmt = "popup.attendance.day_fmt";
        public const string PopupAttendanceStreakFmt = "popup.attendance.streak_fmt";
        public const string PopupAchievementTitle = "popup.achievement.title";
        public const string PopupAccountBtnCopyPid = "popup.account.btn_copy_pid";
        public const string PopupAccountBtnPrivacy = "popup.account.btn_privacy";
        public const string PopupAccountBtnTerms = "popup.account.btn_terms";
        public const string PopupAccountTitle = "popup.account.title";
        public const string PopupAccountLabelPid = "popup.account.label_pid";
        public const string PopupStageInfoDifficultyEasy = "popup.stage_info.difficulty_easy";
        public const string PopupStageInfoDifficultyNormal = "popup.stage_info.difficulty_normal";
        public const string PopupStageInfoDifficultyHard = "popup.stage_info.difficulty_hard";
        public const string PopupStageInfoDifficultyFmt = "popup.stage_info.difficulty_fmt";
        public const string PopupStageInfoTypesFmt = "popup.stage_info.types_fmt";
        public const string PopupFailBtnAddLane = "popup.fail.btn_add_lane";
        public const string PopupFailBtnShuffle = "popup.fail.btn_shuffle";
        public const string PopupResultRewards = "popup.result.rewards";
        public const string PopupFailShuffleConfirmFmt = "popup.fail.shuffle_confirm_fmt";
        public const string PopupSessionInvalidTitle = "popup.session_invalid.title";
        public const string PopupSessionInvalidBody = "popup.session_invalid.body";
        public const string PopupWeeklyMissionTitle = "popup.weekly_mission.title";
        public const string PopupWeeklyMissionEpFmt = "popup.weekly_mission.ep_fmt";
        public const string PopupWeeklyMissionEpRewardFmt = "popup.weekly_mission.ep_reward_fmt";
        public const string PopupWeeklyMissionDaysLeftFmt = "popup.weekly_mission.days_left_fmt";
        public const string PopupWeeklyMissionProgressFmt = "popup.weekly_mission.progress_fmt";
        public const string PopupWeeklyMissionBtnClaimFmt = "popup.weekly_mission.btn_claim_fmt";
        public const string PopupWeeklyMissionClaimed = "popup.weekly_mission.claimed";
        public const string PopupWeeklyMissionLocked = "popup.weekly_mission.locked";
        public const string PopupBoosterBuyTitle = "popup.booster_buy.title";
        public const string PopupBoosterBuyBodyFmt = "popup.booster_buy.body_fmt";
        public const string PopupAttendanceClaimedToday = "popup.attendance.claimed_today";
        public const string PopupExitTitle = "popup.exit.title";
        public const string PopupExitBody = "popup.exit.body";

        // toast
        public const string ToastAccountAlreadyActive = "toast.account_already_active";
        public const string ToastInsufficientGold = "toast.insufficient_gold";
        public const string ToastStageLocked = "toast.stage_locked";
        public const string ToastBoosterPurchased = "toast.booster_purchased";
        public const string ToastAddLaneGranted = "toast.add_lane_granted";
        public const string ToastAdCancelled = "toast.ad_cancelled";
        public const string ToastAdServiceUnavailable = "toast.ad_service_unavailable";
        public const string ToastStuckResolved = "toast.stuck_resolved";
        public const string ToastChapterUnlockRequirement = "toast.chapter_unlock_requirement";
        public const string ToastChestClaimed = "toast.chest_claimed";
        public const string ToastNicknameLengthError = "toast.nickname_length_error";
        public const string ToastNicknameCharError = "toast.nickname_char_error";
        public const string ToastNicknameUpdated = "toast.nickname_updated";
        public const string ToastNicknameUpdateFailed = "toast.nickname_update_failed";
        public const string ToastThemeNotEnoughGold = "toast.theme_not_enough_gold";
        public const string ToastThemeEquipped = "toast.theme_equipped";
        public const string ToastThemeEquipFailed = "toast.theme_equip_failed";
        public const string ToastThemeUnlocked = "toast.theme_unlocked";
        public const string ToastAvatarNotEnoughGold = "toast.avatar_not_enough_gold";
        public const string ToastAvatarEquipped = "toast.avatar_equipped";
        public const string ToastAvatarEquipFailed = "toast.avatar_equip_failed";
        public const string ToastAvatarUnlocked = "toast.avatar_unlocked";
        public const string ToastGoogleSigninNotConfigured = "toast.google_signin_not_configured";
        public const string ToastGoogleSigninUnavailable = "toast.google_signin_unavailable";
        public const string ToastAccountLinked = "toast.account_linked";
        public const string ToastAccountSwitched = "toast.account_switched";
        public const string ToastGoogleSigninAndroidOnly = "toast.google_signin_android_only";
        public const string ToastItemSpendFailed = "toast.item_spend_failed";
        public const string ToastChestClaimFailed = "toast.chest_claim_failed";
        public const string ToastIapPurchaseSuccess = "toast.iap_purchase_success";
        public const string ToastIapAlreadyOwned = "toast.iap_already_owned";
        public const string ToastIapLimitReached = "toast.iap_limit_reached";
        public const string ToastAchievementUnlockedFmt = "toast.achievement_unlocked_fmt";
        public const string ToastPidCopied = "toast.pid_copied";
        public const string ToastBoosterNeedPurchase = "toast.booster_need_purchase";
        public const string ToastNoSolution = "toast.no_solution";
        public const string ToastIapPurchaseFailed = "toast.iap_purchase_failed";

        // lobby
        public const string LobbyRankingStagesTitle = "lobby.ranking.stages_title";
        public const string LobbyRankingStageTitle = "lobby.ranking.stage_title";
        public const string LobbyRankingMyRankEmpty = "lobby.ranking.my_rank_empty";
        public const string LobbyRankingMyRankFormat = "lobby.ranking.my_rank_format";
        public const string LobbyRankingLoading = "lobby.ranking.loading";
        public const string LobbyRankingNoData = "lobby.ranking.no_data";
        public const string LobbyRankingDefaultTitle = "lobby.ranking.default_title";
        public const string LobbyRankingUnavailable = "lobby.ranking.unavailable";
        public const string LobbyRankingTabStages = "lobby.ranking.tab_stages";
        public const string LobbyRankingTabMaxStage = "lobby.ranking.tab_max_stage";
        public const string LobbyRankingDescStage = "lobby.ranking.desc_stage";
        public const string LobbyRankingTabPerfect = "lobby.ranking.tab_perfect";
        public const string LobbyRankingPerfectTitle = "lobby.ranking.perfect_title";
        public const string LobbyRankingDescPerfect = "lobby.ranking.desc_perfect";
        public const string LobbyRankingTabWeekly = "lobby.ranking.tab_weekly";
        public const string LobbyRankingWeeklyTitle = "lobby.ranking.weekly_title";
        public const string LobbyRankingDescWeekly = "lobby.ranking.desc_weekly";

        // ingame
        public const string IngameMovesLabel = "ingame.moves_label";
        public const string IngameSignalsLabel = "ingame.signals_label";
        public const string IngameBestLabel = "ingame.best_label";

        // nav
        public const string NavHome = "nav.home";
        public const string NavShop = "nav.shop";
        public const string NavRanking = "nav.ranking";

        // item
        public const string ItemNameAddLane = "item.name.add_lane";
        public const string ItemDescAddLane = "item.desc.add_lane";
        public const string ItemNameShuffle = "item.name.shuffle";
        public const string ItemDescShuffle = "item.desc.shuffle";
        public const string ItemNameUndo = "item.name.undo";
        public const string ItemDescUndo = "item.desc.undo";

        // tut
        public const string TutSelectChip = "tut.select_chip";
        public const string TutMoveChip = "tut.move_chip";
        public const string TutMovesExplain = "tut.moves_explain";
        public const string TutSignalPanelExplain = "tut.signal_panel_explain";
        public const string TutFreeSort = "tut.free_sort";
        public const string TutLockedLaneWhat = "tut.locked_lane_what";
        public const string TutBlindLaneWhat = "tut.blind_lane_what";
        public const string TutFrozenChipWhat = "tut.frozen_chip_what";
        public const string TutRelayNodeWhat = "tut.relay_node_what";
        public const string TutLockedLaneIntro = "tut.locked_lane_intro";
        public const string TutBlindLaneReveal = "tut.blind_lane_reveal";
        public const string TutRelayFirstNode = "tut.relay_first_node";
        public const string TutRelayNextNode = "tut.relay_next_node";
        public const string TutOverloadChipIntro = "tut.overload_chip_intro";
        public const string TutOverloadChipWhat = "tut.overload_chip_what";
        public const string TutBoosterHintPrompt = "tut.booster_hint_prompt";

        // chapter
        public const string ChapterNameFmt = "chapter.name_fmt";
        public const string ChapterLocked = "chapter.locked";

        // currency
        public const string CurrencyDescGold = "currency.desc.gold";

        // shop
        public const string ShopComingSoon = "shop.coming_soon";
        public const string ShopStarterPack = "shop.starter_pack";
        public const string ShopItemBundle = "shop.item_bundle";
        public const string ShopRemoveAds = "shop.remove_ads";
        public const string ShopIapTitle = "shop.iap.title";
        public const string ShopIapPackages = "shop.iap.packages";
        public const string ShopIapNoAdsTitle = "shop.iap.no_ads.title";
        public const string ShopIapNoAdsDesc = "shop.iap.no_ads.desc";
        public const string ShopIapNoAdsPrice = "shop.iap.no_ads.price";
        public const string ShopIapStarterTitle = "shop.iap.starter.title";
        public const string ShopIapStarterDesc = "shop.iap.starter.desc";
        public const string ShopIapStarterPrice = "shop.iap.starter.price";
        public const string ShopIapMasterTitle = "shop.iap.master.title";
        public const string ShopIapMasterDesc = "shop.iap.master.desc";
        public const string ShopIapMasterPrice = "shop.iap.master.price";
        public const string ShopIapPurchased = "shop.iap.purchased";
        public const string ShopRewardNoAds = "shop.reward.no_ads";
        public const string ShopIapTagBestValue = "shop.iap.tag.best_value";
        public const string ShopIapTagPopular = "shop.iap.tag.popular";
        public const string ShopIapTagBestBuy = "shop.iap.tag.best_buy";
        public const string ShopIapLimitDaily = "shop.iap.limit.daily";
        public const string ShopIapLimitWeekly = "shop.iap.limit.weekly";
        public const string ShopIapLimitMonthly = "shop.iap.limit.monthly";
        public const string ShopIapLimitNone = "shop.iap.limit.none";
        public const string ShopCategorySpecialOffer = "shop.category.special_offer";
        public const string ShopCategoryBundle = "shop.category.bundle";
        public const string ShopCosmeticSectionTitle = "shop.cosmetic.section_title";
        public const string ShopCosmeticTabChip = "shop.cosmetic.tab_chip";
        public const string ShopCosmeticTabLane = "shop.cosmetic.tab_lane";
        public const string ShopCosmeticTabBoard = "shop.cosmetic.tab_board";
        public const string ShopCosmeticBtnBuyApply = "shop.cosmetic.btn_buy_apply";
        public const string ShopCosmeticBtnApply = "shop.cosmetic.btn_apply";
        public const string ShopCosmeticApplied = "shop.cosmetic.applied";
        public const string ShopCosmeticLockedAchievement = "shop.cosmetic.locked_achievement";
        public const string ShopCosmeticLockedAttendance = "shop.cosmetic.locked_attendance";
        public const string ShopCosmeticLockedChallenge = "shop.cosmetic.locked_challenge";
        public const string ShopAvatarLockedReward = "shop.avatar.locked_reward";
        public const string ShopTabProduct = "shop.tab.product";
        public const string ShopTabSkin = "shop.tab.skin";
        public const string ShopTabAvatar = "shop.tab.avatar";
        public const string ShopIapBundleSmallTitle = "shop.iap.bundle_small.title";
        public const string ShopIapBundleSmallDesc = "shop.iap.bundle_small.desc";
        public const string ShopIapBundleSmallPrice = "shop.iap.bundle_small.price";
        public const string ShopIapBundleNormalTitle = "shop.iap.bundle_normal.title";
        public const string ShopIapBundleNormalDesc = "shop.iap.bundle_normal.desc";
        public const string ShopIapBundleNormalPrice = "shop.iap.bundle_normal.price";
        public const string ShopIapBundleLargeTitle = "shop.iap.bundle_large.title";
        public const string ShopIapBundleLargeDesc = "shop.iap.bundle_large.desc";
        public const string ShopIapBundleLargePrice = "shop.iap.bundle_large.price";

        // cosmetic
        public const string CosmeticChipDefaultName = "cosmetic.chip_default.name";
        public const string CosmeticChipDefaultDesc = "cosmetic.chip_default.desc";
        public const string CosmeticChipHexName = "cosmetic.chip_hex.name";
        public const string CosmeticChipHexDesc = "cosmetic.chip_hex.desc";
        public const string CosmeticChipCrystalName = "cosmetic.chip_crystal.name";
        public const string CosmeticChipCrystalDesc = "cosmetic.chip_crystal.desc";
        public const string CosmeticChipRetroName = "cosmetic.chip_retro.name";
        public const string CosmeticChipRetroDesc = "cosmetic.chip_retro.desc";
        public const string CosmeticChipNeonName = "cosmetic.chip_neon.name";
        public const string CosmeticChipNeonDesc = "cosmetic.chip_neon.desc";
        public const string CosmeticChipPlatinumName = "cosmetic.chip_platinum.name";
        public const string CosmeticChipPlatinumDesc = "cosmetic.chip_platinum.desc";
        public const string CosmeticChipGhostName = "cosmetic.chip_ghost.name";
        public const string CosmeticChipGhostDesc = "cosmetic.chip_ghost.desc";
        public const string CosmeticChipDailyName = "cosmetic.chip_daily.name";
        public const string CosmeticChipDailyDesc = "cosmetic.chip_daily.desc";
        public const string CosmeticLaneDefaultName = "cosmetic.lane_default.name";
        public const string CosmeticLaneDefaultDesc = "cosmetic.lane_default.desc";
        public const string CosmeticLaneHoloName = "cosmetic.lane_holo.name";
        public const string CosmeticLaneHoloDesc = "cosmetic.lane_holo.desc";
        public const string CosmeticLaneBronzeName = "cosmetic.lane_bronze.name";
        public const string CosmeticLaneBronzeDesc = "cosmetic.lane_bronze.desc";
        public const string CosmeticLaneCrystalName = "cosmetic.lane_crystal.name";
        public const string CosmeticLaneCrystalDesc = "cosmetic.lane_crystal.desc";
        public const string CosmeticLaneTerminalName = "cosmetic.lane_terminal.name";
        public const string CosmeticLaneTerminalDesc = "cosmetic.lane_terminal.desc";
        public const string CosmeticLaneGhostName = "cosmetic.lane_ghost.name";
        public const string CosmeticLaneGhostDesc = "cosmetic.lane_ghost.desc";
        public const string CosmeticBoardDefaultName = "cosmetic.board_default.name";
        public const string CosmeticBoardDefaultDesc = "cosmetic.board_default.desc";
        public const string CosmeticBoardVoidName = "cosmetic.board_void.name";
        public const string CosmeticBoardVoidDesc = "cosmetic.board_void.desc";
        public const string CosmeticBoardQuantumName = "cosmetic.board_quantum.name";
        public const string CosmeticBoardQuantumDesc = "cosmetic.board_quantum.desc";
        public const string CosmeticBoardRetroDosName = "cosmetic.board_retro_dos.name";
        public const string CosmeticBoardRetroDosDesc = "cosmetic.board_retro_dos.desc";
        public const string CosmeticBoardCircuitName = "cosmetic.board_circuit.name";
        public const string CosmeticBoardCircuitDesc = "cosmetic.board_circuit.desc";
        public const string CosmeticBoardVintageName = "cosmetic.board_vintage.name";
        public const string CosmeticBoardVintageDesc = "cosmetic.board_vintage.desc";
        public const string CosmeticBoardCollectorName = "cosmetic.board_collector.name";
        public const string CosmeticBoardCollectorDesc = "cosmetic.board_collector.desc";
        public const string CosmeticBoardChallengeName = "cosmetic.board_challenge.name";
        public const string CosmeticBoardChallengeDesc = "cosmetic.board_challenge.desc";
        public const string CosmeticBoardSpectrumName = "cosmetic.board_spectrum.name";
        public const string CosmeticBoardSpectrumDesc = "cosmetic.board_spectrum.desc";
        public const string CosmeticChipPrismName = "cosmetic.chip_prism.name";
        public const string CosmeticChipPrismDesc = "cosmetic.chip_prism.desc";

        // home
        public const string HomeBadgeAttendance = "home.badge.attendance";
        public const string HomeBadgeWeeklyMission = "home.badge.weekly_mission";

        // achievement
        public const string AchievementTabProgression = "achievement.tab.progression";
        public const string AchievementTabSkill = "achievement.tab.skill";
        public const string AchievementTabDedication = "achievement.tab.dedication";
        public const string AchievementTabCollection = "achievement.tab.collection";
        public const string AchievementBtnClaim = "achievement.btn_claim";
        public const string AchievementProgressFmt = "achievement.progress_fmt";
        public const string AchievementCompleted = "achievement.completed";

        // ach
        public const string AchPrg01Name = "ach.prg_01.name";
        public const string AchPrg01Desc = "ach.prg_01.desc";
        public const string AchPrg02Name = "ach.prg_02.name";
        public const string AchPrg02Desc = "ach.prg_02.desc";
        public const string AchPrg03Name = "ach.prg_03.name";
        public const string AchPrg03Desc = "ach.prg_03.desc";
        public const string AchPrg04Name = "ach.prg_04.name";
        public const string AchPrg04Desc = "ach.prg_04.desc";
        public const string AchPrg05Name = "ach.prg_05.name";
        public const string AchPrg05Desc = "ach.prg_05.desc";
        public const string AchPrg06Name = "ach.prg_06.name";
        public const string AchPrg06Desc = "ach.prg_06.desc";
        public const string AchSkl01Name = "ach.skl_01.name";
        public const string AchSkl01Desc = "ach.skl_01.desc";
        public const string AchSkl02Name = "ach.skl_02.name";
        public const string AchSkl02Desc = "ach.skl_02.desc";
        public const string AchSkl03Name = "ach.skl_03.name";
        public const string AchSkl03Desc = "ach.skl_03.desc";
        public const string AchSkl04Name = "ach.skl_04.name";
        public const string AchSkl04Desc = "ach.skl_04.desc";
        public const string AchSkl05Name = "ach.skl_05.name";
        public const string AchSkl05Desc = "ach.skl_05.desc";
        public const string AchSkl06Name = "ach.skl_06.name";
        public const string AchSkl06Desc = "ach.skl_06.desc";
        public const string AchDed01Name = "ach.ded_01.name";
        public const string AchDed01Desc = "ach.ded_01.desc";
        public const string AchDed02Name = "ach.ded_02.name";
        public const string AchDed02Desc = "ach.ded_02.desc";
        public const string AchDed03Name = "ach.ded_03.name";
        public const string AchDed03Desc = "ach.ded_03.desc";
        public const string AchDed04Name = "ach.ded_04.name";
        public const string AchDed04Desc = "ach.ded_04.desc";
        public const string AchDed05Name = "ach.ded_05.name";
        public const string AchDed05Desc = "ach.ded_05.desc";
        public const string AchDed06Name = "ach.ded_06.name";
        public const string AchDed06Desc = "ach.ded_06.desc";
        public const string AchCol01Name = "ach.col_01.name";
        public const string AchCol01Desc = "ach.col_01.desc";
        public const string AchCol02Name = "ach.col_02.name";
        public const string AchCol02Desc = "ach.col_02.desc";
        public const string AchCol03Name = "ach.col_03.name";
        public const string AchCol03Desc = "ach.col_03.desc";
        public const string AchCol04Name = "ach.col_04.name";
        public const string AchCol04Desc = "ach.col_04.desc";
        public const string AchCol05Name = "ach.col_05.name";
        public const string AchCol05Desc = "ach.col_05.desc";

        // gimmick
        public const string GimmickLockedLaneName = "gimmick.locked_lane.name";
        public const string GimmickLockedLaneDesc = "gimmick.locked_lane.desc";
        public const string GimmickBlindLaneName = "gimmick.blind_lane.name";
        public const string GimmickBlindLaneDesc = "gimmick.blind_lane.desc";
        public const string GimmickRelayNodeName = "gimmick.relay_node.name";
        public const string GimmickRelayNodeDesc = "gimmick.relay_node.desc";
        public const string GimmickOverloadChipName = "gimmick.overload_chip.name";
        public const string GimmickOverloadChipDesc = "gimmick.overload_chip.desc";
        public const string GimmickSectionHeader = "gimmick.section_header";

        // event
        public const string EventWmStage10Name = "event.wm.stage10.name";
        public const string EventWmStage10Desc = "event.wm.stage10.desc";
        public const string EventWmPerfect3Name = "event.wm.perfect3.name";
        public const string EventWmPerfect3Desc = "event.wm.perfect3.desc";
        public const string EventWmNoboost5Name = "event.wm.noboost5.name";
        public const string EventWmNoboost5Desc = "event.wm.noboost5.desc";
        public const string EventWmProgress5Name = "event.wm.progress5.name";
        public const string EventWmProgress5Desc = "event.wm.progress5.desc";
        public const string EventWmBest5Name = "event.wm.best5.name";
        public const string EventWmBest5Desc = "event.wm.best5.desc";
    }
}
#endif
