// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/achievement/achievement.csv
using ProjectFill.Contracts.GameTypes;

namespace ProjectFill.Domain.StaticData;

public class AchievementData
{
    public string AchievementId { get; set; } = "";
    public AchievementCategory Category { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
    public AchievementTier Tier { get; set; }
    public int RewardGroupId { get; set; }
    public AchievementConditionType ConditionType { get; set; }
    public int ConditionValue { get; set; }
    public int SortOrder { get; set; }
}