// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/avatar/avatar.csv

namespace ProjectFill.Domain.StaticData;

public class AvatarData
{
    public int Id { get; set; }
    public string ResourceName { get; set; } = "";
    public int UnlockCost { get; set; }
    public string UnlockType { get; set; } = "";
}