// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/stage/chapter.csv

namespace ProjectFill.Domain.StaticData;

public class ChapterData
{
    public int ChapterId { get; set; }
    public int DisplayOrder { get; set; }
    public int UnlockChapterId { get; set; }
    public int BgThemeId { get; set; }
    public int ChestRewardGroupId { get; set; }
}