// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/common/color_palette.csv

namespace ProjectFill.Domain.StaticData;

public class ColorPaletteData
{
    public byte Id { get; set; }
}