// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/cosmetic/cosmetic_item.csv
using ProjectFill.Contracts.GameTypes;

namespace ProjectFill.Domain.StaticData;

public class CosmeticItemData
{
    public string CosmeticId { get; set; } = "";
    public CosmeticCategory Category { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
    public CosmeticUnlockType UnlockType { get; set; }
    public int UnlockCost { get; set; }
    public string UnlockConditionId { get; set; } = "";
    public string PreviewRes { get; set; } = "";
    public int SortOrder { get; set; }
}