// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/daily_login/daily_login_milestone.csv

namespace ProjectFill.Domain.StaticData;

public class DailyLoginMilestoneData
{
    public int Id { get; set; }
    public int ThresholdDays { get; set; }
    public int RewardGroupId { get; set; }
    public string CosmeticConditionId { get; set; } = "";
}