// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/daily_login/daily_login_reward.csv
using ProjectFill.Contracts.GameTypes;

namespace ProjectFill.Domain.StaticData;

public class DailyLoginRewardData
{
    public int Id { get; set; }
    public AttendanceCycleType CycleType { get; set; }
    public int Day { get; set; }
    public int RewardGroupId { get; set; }
    public int SortOrder { get; set; }
}