// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/common/dynamic_resource.csv

namespace ProjectFill.Domain.StaticData;

public class DynamicResourceData
{
    public int Id { get; set; }
    public string ResourceKey { get; set; } = "";
    public string SpritePath { get; set; } = "";
    public string Category { get; set; } = "";
    public string Comment { get; set; } = "";
}