// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/shop/iap_product.csv
using ProjectFill.Contracts.GameTypes;

namespace ProjectFill.Domain.StaticData;

public class IapProductData
{
    public int Id { get; set; }
    public string StoreProductId { get; set; } = "";
    public IapProductType ProductType { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
    public double PriceUsd { get; set; }
    public string IconRes { get; set; } = "";
    public int RewardGroupId { get; set; }
    public int PurchaseLimit { get; set; }
    public PurchaseResetPeriod ResetPeriod { get; set; }
    public int SortOrder { get; set; }
    public bool IsEnabled { get; set; }
}