// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/item/item.csv

namespace ProjectFill.Domain.StaticData;

public class ItemData
{
    public int Id { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
    public int Price { get; set; }
}