// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/reward/reward_group.csv

namespace ProjectFill.Domain.StaticData;

public class RewardGroupData
{
    public int Id { get; set; }
    public int RewardGroupId { get; set; }
    public int Version { get; set; }
    public string DisplayKey { get; set; } = "";
    public bool IsEnabled { get; set; }
}