// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/stage/stage.csv

namespace ProjectFill.Domain.StaticData;

public class StageData
{
    public int StageId { get; set; }
    public int ChapterId { get; set; }
    public int StageOrder { get; set; }
    public int Difficulty { get; set; }
    public int RewardGroupId { get; set; }
}