// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/event/weekly_mission_track.csv

namespace ProjectFill.Domain.StaticData;

public class WeeklyMissionTrackData
{
    public int EpThreshold { get; set; }
    public int RewardGroupId { get; set; }
    public int SortOrder { get; set; }
}