// AUTO-GENERATED by gen:data — do not edit
// Source: shared/datas/event/weekly_mission_pool.csv
using ProjectFill.Contracts.GameTypes;

namespace ProjectFill.Domain.StaticData;

public class WeeklyMissionPoolData
{
    public string MissionId { get; set; } = "";
    public WeeklyMissionConditionType ConditionType { get; set; }
    public int ConditionValue { get; set; }
    public int EpReward { get; set; }
    public string NameKey { get; set; } = "";
    public string DescKey { get; set; } = "";
}